### ISSUE TITLE
I'm crashing/timing out on os X

### ISSUE THREAD

**Issue by mrlowe** [robert-butts/slackterm#9] opened 2015-11-06 23:04 UTC
Just leaving a note for myself, so I can see what's up.

```
panic: Unexpected Response: 408 REQUEST_TIMEOUT


goroutine 1 [running]:
log.Panicln(0xc820053db0, 0x1, 0x1)
    /usr/local/go/src/log/log.go:334 +0xc1
main.EnterTheGui(0xc820074500, 0x34, 0xc820076360, 0xc8200763c0, 0xc820076480, 0xc8200764e0, 0xc820076420, 0xc8200765a0, 0xc820076600)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/gui.go:40 +0x461
main.main()
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/slackterm.go:36 +0x55c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [select]:
main.channelIdManager(0xc820074500, 0x34, 0xc820076360, 0xc8200763c0, 0xc820076420)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/channel_manager.go:48 +0x870
created by main.StartChannelIdManager
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/channel_manager.go:84 +0xc5

goroutine 22 [select]:
net/http.(*persistConn).roundTrip(0xc820114000, 0xc8200de020, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc8200bc090, 0xc8200dc000, 0xba, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:235 +0x530
net/http.send(0xc8200dc000, 0x6aa508, 0xc8200bc090, 0xc8200ce060, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0x55dd00, 0xc8200dc000, 0x5b, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0x55dd00, 0xc8200dc000, 0x43eea8, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Get(0x55dd00, 0xc8200ce000, 0x5b, 0xc82002c360, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:306 +0xaa
net/http.Get(0xc8200ce000, 0x5b, 0x27, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:281 +0x45
main.GetSlackUsers(0xc820074500, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/slack.go:176 +0xa1
main.userManager(0xc820074500, 0x34, 0xc820076480)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/user_manager.go:29 +0x77
created by main.StartUserManager
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/user_manager.go:56 +0x67

goroutine 23 [select]:
main.messagesManager(0xc820074500, 0x34, 0xc8200764e0, 0xc820076540, 0xc820076480)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/message_manager.go:41 +0x1acb
created by main.StartMessagesManager
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/message_manager.go:80 +0xa2

goroutine 24 [select]:
net/http.(*persistConn).roundTrip(0xc82015c000, 0xc82012c020, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc8200bc090, 0xc820128000, 0xba, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:235 +0x530
net/http.send(0xc820128000, 0x6aa508, 0xc8200bc090, 0xc82010e060, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0x55dd00, 0xc820128000, 0x5a, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0x55dd00, 0xc820128000, 0x43eea8, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Get(0x55dd00, 0xc82010e000, 0x5a, 0xc82002d2c0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:306 +0xaa
net/http.Get(0xc82010e000, 0x5a, 0x26, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:281 +0x45
main.slackRtmStart(0xc820074500, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/rtm.go:63 +0x9d
main.ConnectToSlackRtm(0xc820074500, 0x34, 0x0, 0x0, 0x0)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/rtm.go:94 +0x52
main.SlackRtmHandler(0xc820074500, 0x34, 0xc820076540, 0xc8200765a0, 0xc820076600)
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/rtm.go:217 +0x49
created by main.StartSlackRtmHandler
    /Users/matt/Code/go/src/github.com/robert-butts/slackterm/rtm.go:235 +0xa2

goroutine 25 [select, locked to thread]:
runtime.gopark(0x43f270, 0xc82002df28, 0x3aa0d8, 0x6, 0x3e318, 0x2)
    /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002df28, 0x0, 0x18)
    /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002df28)
    /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 54 [select]:
net/http.(*persistConn).writeLoop(0xc82015c000)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 53 [runnable]:
net.(*netFD).Read(0xc82013e070, 0xc8200c4800, 0x400, 0x400, 0x62, 0x0, 0x0)
    /usr/local/go/src/net/fd_unix.go:240 +0x323
net.(*conn).Read(0xc820088060, 0xc8200c4800, 0x400, 0x400, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82007d320, 0x6aa748, 0xc820088060, 0x5, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820192000, 0x43f317, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820192000, 0xc820574000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x1700090, 0xc820192000, 0xc82015c058, 0xc820574000, 0x1000, 0x1000, 0xc82010ec60, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82015a7a0, 0xc820574000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82010eb40)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82010eb40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82015c000)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 30 [IO wait]:
net.runtime_pollWait(0x1160e80, 0x72, 0xc8200780a0)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820072920, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820072920, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200728c0, 0xc8201a0400, 0x400, 0x400, 0x0, 0x6a6028, 0xc8200780a0)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200e0028, 0xc8201a0400, 0x400, 0x400, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8200da420, 0x6aa748, 0xc8200e0028, 0x5, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201962c0, 0x43f317, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201962c0, 0xc8201cf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x1700090, 0xc8201962c0, 0xc820114058, 0xc8201cf000, 0x1000, 0x1000, 0xc82053a8a0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8201dd480, 0xc8201cf000, 0x1000, 0x1000, 0xc820069200, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820077680)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820077680, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820114000)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 31 [select]:
net/http.(*persistConn).writeLoop(0xc820114000)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
```

**Comment by rob05c** [comment] 2015-11-06 23:19
The http.Get() is timing out. 

https://github.com/robert-butts/slackterm/blob/master/slack.go#L103

Is there any chance your firewall is blocking outgoing https requests from untrusted apps?

What happens when you try curl?

curl https://slack.com/api/channels.list?token=yourtoken

**Comment by rob05c** [comment] 2015-11-06 23:25
Ah, I'm getting the same thing for abilenefriends (but not milsoft). I'm looking into it.

**Comment by rob05c** [comment] 2015-11-06 23:36
Does your token file have a newline in it? 

That was my problem, and I had exactly your symptoms. The token file must contain the token and nothing else, no newline, no whitespace.

**Comment by rob05c** [comment] 2016-05-27 22:56
I made token reading trim spaces and newlines, and I can't reproduce, so I'm closing this. Reopen if it's still reproducible.

**Closed as completed by rob05c** 2016-05-27 22:56 UTC
Labels: bug
